### ISSUE TITLE
2.json missing

### ISSUE THREAD

**Issue by BlueMSX** [olauncher/olauncher#79]
after much troubleshooting in trying to get the launcher to start Minecraft, i was halted with this error in the launcher log.

[22:37:33 FATAL]: Fatal error launching game. Report this to https://github.com/olauncher/olauncher/issues/new please!
java.io.FileNotFoundException: C:\Users\Mumu\AppData\Roaming\.minecraft\assets\indexes\2.json (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_411]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_411]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_411]
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:2388) ~[patched.jar:1.7.3]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2506) ~[patched.jar:1.7.3]
	at net.minecraft.launcher.Launcher.cleanupOrphanedAssets(Launcher.java:362) ~[patched.jar:1.7.3]
	at net.minecraft.launcher.Launcher.performCleanups(Launcher.java:615) ~[patched.jar:1.7.3]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:219) ~[patched.jar:1.7.3]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:292) ~[patched.jar:1.7.3]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:150) ~[patched.jar:1.7.3]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:16) ~[patched.jar:1.7.3]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:111) ~[patched.jar:1.7.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_411]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_411]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_411]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_411]
[22:37:33 INFO]: Deleting C:\Users\Mumu\AppData\Roaming\.minecraft\versions\1.20.6\1.20.6-natives-14120131965700

I was unable to figure out what more I needed to do, posting here was the next logical step.

**Comment by bigfoot547** [comment]
Can you put the stack trace in code tags? (surround it with \`\`\`)

**Comment by BlueMSX** [comment]
> Can you put the stack trace in code tags? (surround it with ```)

how do i do that?

**Comment by DevBefell** [comment]
This issue is fixed in my PR for internal overhaul, it was missing a check if the file exists.

**Comment by BlueMSX** [comment]
> This issue is fixed in my PR for internal overhaul, it was missing a check if the file exists.

how do i fix it on my end?

**Comment by DevBefell** [comment]
Currently, you can try to create a `2.json` file in that folder `%HOME%/.minecraft/assets/indexes` temporally.

**Comment by BlueMSX** [comment]
> Currently, you can try to create a `2.json` file in that folder `%HOME%/.minecraft/assets/indexes` temporally.

it's still not working, but thank you all for your help anyways!
